# Generated by Django 6.0.3 on 2026-04-01 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='anomalies.anomalyresult')),
            ],
        ),
    ]
