# Generated by Django 6.0.3 on 2026-04-01 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_score', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.apirequestlog')),
            ],
        ),
    ]
